services:
  - type: web
    name: n8n
    env: docker
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        fromService:
          name: n8n
          type: web
          property: host
      - key: WEBHOOK_URL
        sync: false
      - key: GENERIC_TIMEZONE
        value: America/New_York
      - key: N8N_LOG_LEVEL
        value: info
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

databases:
  - name: n8n-db
    plan: free
    databaseName: n8n
    user: n8n
